Update deno.yml

diff --git a/.github/workflows/deno.yml b/.github/workflows/deno.yml
--- a/.github/workflows/deno.yml
+++ b/.github/workflows/deno.yml
@@ -1,40 +1,40 @@
- 姓名                      : 上游同步
+name: Upstream Sync
 
- 准许                      :
-  目录                           : 书写
+permissions:
+  contents: write
 
-在…上                          :
-  附表                       :
-    - 克龙                       : "0 0 * * *"                     #每天
-  工作流程                 :
+on:
+  schedule:
+    - cron: "0 0 * * *" # every day
+  workflow_dispatch:
 
-乔布斯              :
-  sync_latest_from_upstream          :
-    姓名         : 来自上游回购的最新承诺
-    逃跑        : 最新的
-    如果       : $    {         } { github.event.repository.fork }     
+jobs:
+  sync_latest_from_upstream:
+    name: Sync latest commits from upstream repo
+    runs-on: ubuntu-latest
+    if: ${{ github.event.repository.fork }}
 
-    台阶    :
-      #步骤1:运行一个标准的结账行动
-      - 姓名   : 核对目标回购
-        使用  : 行动/结账@v3
+    steps:
+      # Step 1: run a standard checkout action
+      - name: Checkout target repo
+        uses: actions/checkout@v3
 
-      #步骤2:运行同步动作
-      -              姓名              : 上游变化
-        身份证             : 同步控制
-        使用            : aormsby/Fork-Sync-With-Upstream-action@v3.4
-        与…有关           :
-          上游的          : 工人/工人
-          上游_同步_分支         : 主要的
-          目标_同步_分支        : 主要的
-          目标       : $ {      { 秘密。吉苏布_托肯 }     }     #自动生成,无需设置
+      # Step 2: run the sync action
+      - name: Sync upstream changes
+        id: sync
+        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
+        with:
+          upstream_sync_repo: cmliu/CF-Workers-docker.io
+          upstream_sync_branch: main
+          target_sync_branch: main
+          target_repo_token: ${{ secrets.GITHUB_TOKEN }} # automatically generated, no need to set
 
-          #将测试_模式真正用于运行测试,而不是真正的操作!!
-          试验模式   : 假的
+          # Set test_mode true to run tests instead of the true action!!
+          test_mode: false
 
-      - 姓名  : 同步检查
-        如果   : failure()
-        跑  : |
+      - name: Sync check
+        if: failure()
+        run: |
           echo "[Error] 由于上游仓库的 workflow 文件变更，导致 GitHub 自动暂停了本次自动更新，你需要手动 Sync Fork 一次，详细教程请查看项目README.md "
-          由于上游存储库的工作流文件发生了变化,GUUUB自动暂停了预定的自动更新。你需要手动同步你的叉。请参阅项目资料。"
-          1号出口
+          echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork. Please refer to the project README.md for instructions. "
+          exit 1
